kind: Service
apiVersion: v1
metadata:
  name: mutating
  namespace: default
spec:
  selector:
    app: mutating
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: mutating
  labels:
    app: mutating
spec:
  containers:
  - name: mutating
    image: jinseon/mutating:1.0
